# Generated by Django 4.2.4 on 2023-09-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('idRace', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('lapNumber', models.SmallIntegerField()),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('idRacer', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('dni', models.PositiveIntegerField(unique=True)),
                ('birth', models.DateField()),
                ('cel', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='raceResult',
            fields=[
                ('idStartRace', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lap_num', models.PositiveSmallIntegerField()),
                ('lap', models.CharField(verbose_name=8)),
                ('idRace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoCronos.race')),
                ('idRacer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MotoCronos.racer')),
            ],
        ),
    ]
