# Generated by Django 4.2.4 on 2023-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoCronos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
