# Generated by Django 4.2.4 on 2023-09-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoCronos', '0002_alter_race_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='cel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='racer',
            name='dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
